name: pay_notify
description: Real-time payment notification app for online merchants and freelancers
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State management
  provider: ^6.0.5
  
  # Supabase
  supabase_flutter: ^2.3.4
  postgrest: ^2.0.0
  
  # Local storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  
  # Network and API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Notification handling
  flutter_local_notifications: ^15.1.0+1
  audioplayers: ^5.2.1
  
  # Utils
  intl: ^0.18.1
  permission_handler: ^10.4.3
  url_launcher: ^6.1.14
  package_info_plus: ^5.0.1
  
  # UI components
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  lottie: ^2.6.0
  
  # Image and Text Recognition
  image_picker: ^1.0.4
  google_ml_kit: ^0.16.2
  camera: ^0.10.5+5
  screenshot: ^2.1.0
  flutter_image_compress: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-Light.ttf
          weight: 300